export interface UserProfile {
  name: string;
  email: string;
  role: string;
  avatarUrl?: string;
}

export interface ShiftLog {
  id: string;
  startTime: string;
  endTime?: string;
  duration?: number; // in seconds
}

export interface BreakLog {
  id: string;
  startTime: string;
  endTime?: string;
  duration?: number; // in seconds
  reason: string;
}

export interface CRMContact {
  id: string;
  name: string;
  email: string;
  phone: string;
  company: string;
  status: 'Lead' | 'Active' | 'Inactive' | 'VIP';
  notes: string;
  lastContactDate: string;
}

export interface TicketResponse {
  id: string;
  ticketId: string;
  text: string;
  author: string;
  createdAt: string;
}

export interface SupportTicket {
  id: string;
  contactId: string;
  contactName: string;
  title: string;
  priority: 'Low' | 'Medium' | 'High' | 'Urgent';
  status: 'Open' | 'In Progress' | 'Resolved' | 'Closed';
  category: 'Billing' | 'Technical' | 'General' | 'Feature Request';
  description: string;
  createdAt: string;
  replies?: TicketResponse[];
}

export interface KBArticle {
  id: string;
  title: string;
  content: string;
  category: string;
  author: string;
  createdAt: string;
  updatedAt: string;
}

export type AgentStatus = 'offline' | 'available' | 'on_break';

export type CallDirection = 'inbound' | 'outbound';
export type CallOutcome = 'connected' | 'missed' | 'voicemail' | 'no_agents_available' | 'in_progress';

export interface CallLogEntry {
  id: string;
  callSid: string;
  fromNumber: string;
  toNumber: string;
  direction: CallDirection;
  digitPressed?: string;
  department?: string;
  routedAgentId?: string;
  routedAgentName?: string;
  outcome: CallOutcome;
  durationSeconds?: number;
  recordingUrl?: string;
  startedAtISO: string;
  endedAtISO?: string;
  summaryCategory?: string;
  summaryRemark?: string;
  summaryComplete?: boolean;
}

export interface IvrMenuOption {
  digit: string;
  label: string;
  department: string;
}

export interface MonthlyShifts {
  morning: string[];
  standardDay: string[];
  lateDay: string[];
  afternoon: string[];
  evening: string[];
  night: string[];
  off: string[];
}

export interface RosterDay {
  id: string;
  date: string; // "YYYY-MM-DD"
  dayOfWeek: string; // e.g., "Monday"
  shifts: MonthlyShifts;
  notes?: string;
  isAutoGenerated?: boolean;
}

export interface AgentCredential {
  agentId: string;
  passwordHash: string; // Plaintext as Password per requirements
  name: string;
  role: 'AGENT' | 'ADMIN';
}

export interface LiveAgentSession {
  id: string;
  agentId?: string;
  name: string;
  loginTime: string;
  clockInTime?: string;
  status: 'offline' | 'available' | 'on_break';
  currentActivity: string;
  lastActive: string;
  shiftTimer?: number;
  breakTimer?: number;
  ipInfo?: string;
  deviceInfo?: string;
  userAgent?: string;
}

export interface AgentPerformanceMetric {
  uniqueCaseId: string;
  transactionKey: string; // e.g. agent01_1721990000000_2026-07-26
  agentId: string;
  agentName: string;
  department: string;
  totalResolved: number;
  ahtSeconds: number;
  ahtFormatted: string;
  csatScore: number;
  slaCompliancePercent: number;
  status: 'Online' | 'On Break' | 'Offline' | 'Idle';
  lastUpdatedISO: string;
  firstContactResolutionPercent?: number;
}

